# -*- coding: utf-8 -*-
#------------------------------------------------------------------------------
# file: $Id$
# desc: metagriffin's standard python makefile
# auth: metagriffin <metagriffin@uberdev.org>
# date: 2013/11/08
# copy: (C) CopyLoose 2013 UberDev <hardcore@uberdev.org>, No Rights Reserved.
#------------------------------------------------------------------------------

test:
	nosetests --verbose

clean:
	find . -iname '*.pyc' -exec rm {} \;
	rm -fr "$(PKGNAME).egg-info" dist

tag:
	@echo "[  ] tagging as version `cat VERSION.txt`..."
	git tag -a "v`cat VERSION.txt`" -m "released v`cat VERSION.txt`"

ci:
	git push
	git push --tags

upload:
	python setup.py sdist upload

#------------------------------------------------------------------------------
# end of $Id$
#------------------------------------------------------------------------------
